import Image from "next/image";
import Link from "next/link";
import { AlertTriangle, ArrowDown, ArrowUpRight, Check, ChevronRight, Clock3, ExternalLink, Gauge, Monitor, Smartphone, Sparkles, Target } from "lucide-react";
import type { AuditRecord, ExpertKey, Finding } from "@/lib/audit/types";
import { Brand } from "@/components/brand";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { ScoreRing } from "@/components/report/score-ring";

const labels: Record<ExpertKey, string> = { conversion: "Conversion", ux: "UX", copywriting: "Copywriting", seo: "SEO", performance: "Performance", accessibility: "Accessibility", trust: "Trust", mobile: "Mobile" };
const pageGoalLabels: Record<string, string> = { "get-leads": "Get leads", "book-demos": "Book demos", "sell": "Sell a product", "signups": "Drive signups", "inform": "Explain / inform" };
const badgeVariant = (impact: Finding["impact"]) => impact === "critical" ? "danger" as const : impact === "high" ? "warning" as const : "secondary" as const;
const metric = (value: number | null | undefined, suffix = "") => value == null ? "—" : `${value < 10 ? value.toFixed(2) : Math.round(value)}${suffix}`;

function Screenshot({ src, mobile }: { src?: string; mobile?: boolean }) {
  if (src) return <div className={`overflow-hidden rounded-xl border bg-muted ${mobile ? "mx-auto max-w-72" : ""}`}><Image src={src} alt={`Annotated ${mobile ? "mobile" : "desktop"} page capture`} width={mobile ? 390 : 1440} height={mobile ? 844 : 1000} sizes={mobile ? "288px" : "(max-width: 1024px) 100vw, 900px"} unoptimized className="h-auto w-full" /></div>;
  return <div className={`relative overflow-hidden rounded-xl border bg-[#eef0f8] p-3 ${mobile ? "mx-auto aspect-[9/16] max-w-64" : "aspect-[16/10]"}`}><div className="h-full rounded-lg bg-white p-4 shadow-sm"><div className="flex gap-1"><i className="size-1.5 rounded-full bg-red-300" /><i className="size-1.5 rounded-full bg-amber-300" /><i className="size-1.5 rounded-full bg-blue-300" /></div><div className="mx-auto mt-[16%] max-w-[75%] text-center"><div className="mx-auto h-2 w-3/4 rounded bg-foreground" /><div className="mx-auto mt-2 h-2 w-1/2 rounded bg-foreground" /><div className="mx-auto mt-4 h-1.5 w-4/5 rounded bg-muted" /><div className="mx-auto mt-1.5 h-1.5 w-3/5 rounded bg-muted" /><div className="mx-auto mt-5 h-6 w-20 rounded-full bg-primary" /></div></div><span className="absolute left-[18%] top-[29%] grid size-7 place-items-center rounded-full bg-primary text-xs font-bold text-white shadow">1</span><span className="absolute left-[43%] top-[54%] grid size-7 place-items-center rounded-full bg-primary text-xs font-bold text-white shadow">2</span></div>;
}

export function ReportView({ audit }: { audit: AuditRecord }) {
  const report = audit.report!;
  const metrics = audit.metrics!;
  return <div className="min-h-screen bg-background">
    <header className="border-b bg-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4 md:px-8"><Brand /><div className="flex items-center gap-3"><Badge variant="outline">Completed</Badge><Link href="/#audit" className="rounded-full bg-foreground px-4 py-2.5 text-xs font-bold text-white">New audit</Link></div></div></header>
    <div className="sticky top-0 z-20 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[1500px] gap-7 overflow-x-auto px-5 text-xs font-bold md:px-8"><a href="#overview" className="border-b-2 border-primary py-4">Overview</a><a href="#priorities" className="py-4 text-muted-foreground">Priorities</a><a href="#evidence" className="py-4 text-muted-foreground">Evidence</a><a href="#analysis" className="py-4 text-muted-foreground">Analysis</a><a href="#copy" className="py-4 text-muted-foreground">Copy</a><a href="#technical" className="py-4 text-muted-foreground">Technical</a></div></div>

    <main>
      <section id="overview" className="hero-glow grid-noise text-white"><div className="mx-auto grid max-w-[1500px] gap-12 px-5 py-16 md:px-8 lg:grid-cols-[1fr_1.25fr] lg:py-20"><div><div className="flex flex-wrap items-center gap-2 text-xs font-bold text-white/45"><span>{new URL(audit.normalizedUrl).hostname}</span><ChevronRight className="size-3" /><span>Goal: {pageGoalLabels[audit.pageGoal] ?? audit.pageGoal}</span></div><h1 className="display mt-5 text-[clamp(4.5rem,8vw,8rem)]">Your website, seen clearly.</h1><p className="mt-7 max-w-xl text-base leading-7 text-white/65">{report.executiveSummary}</p><div className="mt-8 flex flex-wrap gap-4 text-xs text-white/40"><span className="inline-flex items-center gap-2"><Clock3 className="size-3.5" /> Completed report</span><span className="inline-flex items-center gap-2"><Monitor className="size-3.5" /> Desktop + mobile</span></div></div><div className="flex items-center justify-center lg:justify-end"><div className="flex items-center gap-8 rounded-3xl border border-white/10 bg-white/[.04] p-7 backdrop-blur md:p-10"><ScoreRing score={report.overallScore} /><div className="hidden sm:block"><span className="text-xs font-bold uppercase tracking-widest text-primary">Overall score</span><h2 className="mt-2 text-2xl font-bold">Clear potential.<br />Specific leaks.</h2><a href="#priorities" className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-white/60">See what to fix <ArrowDown className="size-3" /></a></div></div></div></div></section>

      <section className="mx-auto max-w-[1500px] px-5 py-14 md:px-8"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{report.sections.map((section) => <Card key={section.key} className="p-5"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-wider text-muted-foreground">{labels[section.key]}</span><strong className="font-mono text-xl">{section.score}</strong></div><Progress value={section.score} aria-label={`${labels[section.key]} score`} className="mt-4" /><p className="mt-4 line-clamp-2 text-xs leading-5 text-muted-foreground">{section.summary}</p></Card>)}</div></section>

      <section id="priorities" className="border-y bg-white"><div className="mx-auto max-w-[1500px] px-5 py-20 md:px-8"><div className="grid gap-10 lg:grid-cols-[.55fr_1.45fr]"><div><span className="eyebrow">Top priorities</span><h2 className="display mt-8 text-7xl md:text-8xl">Do these first.</h2><p className="mt-6 max-w-sm text-sm leading-6 text-muted-foreground">Ranked by expected impact, evidence and effort. Start at one; resist the urge to fix everything at once.</p></div><div className="space-y-3">{report.priorities.map((item, index) => <article key={item.title} className={`rounded-2xl border p-6 md:p-8 ${index === 0 ? "bg-foreground text-white" : "bg-background"}`}><div className="grid gap-5 md:grid-cols-[3rem_1fr_auto]"><span className={`grid size-10 place-items-center rounded-full text-xs font-black ${index === 0 ? "bg-primary text-foreground" : "bg-muted"}`}>0{index + 1}</span><div><div className="flex flex-wrap gap-2"><h3 className="text-lg font-bold">{item.title}</h3><Badge variant={badgeVariant(item.impact)}>{item.impact} impact</Badge><Badge variant="outline" className={index === 0 ? "border-white/20" : ""}>{item.effort} effort</Badge></div><div className={`mt-5 border-l-2 pl-4 text-xs leading-5 ${index === 0 ? "border-white/20 text-white/50" : "text-muted-foreground"}`}><strong className={index === 0 ? "text-white/70" : "text-foreground"}>Evidence: </strong>{item.evidence}</div><p className={`mt-4 text-sm font-bold leading-6 ${index === 0 ? "text-primary" : ""}`}>{item.recommendation}</p></div><ArrowUpRight className="hidden size-5 opacity-30 md:block" /></div></article>)}</div></div></div></section>

      <section id="evidence" className="mx-auto max-w-[1500px] px-5 py-20 md:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><span className="eyebrow">Visual evidence</span><h2 className="display mt-7 text-7xl md:text-8xl">What we saw.</h2></div><p className="max-w-md text-sm leading-6 text-muted-foreground">Markers identify the headline and key actions reviewed. The browser also follows safe, same-site CTA destinations without submitting forms.</p></div><div className="mt-10 grid gap-8 lg:grid-cols-[1.45fr_.55fr]"><div><div className="mb-3 flex items-center gap-2 text-xs font-bold"><Monitor className="size-4" /> Desktop</div><Screenshot src={audit.page?.desktopScreenshotPath} /></div><div><div className="mb-3 flex items-center gap-2 text-xs font-bold"><Smartphone className="size-4" /> Mobile</div><Screenshot src={audit.page?.mobileScreenshotPath} mobile /></div></div>{audit.page?.ctaJourneys?.length ? <div className="mt-12"><h3 className="text-lg font-bold">Conversion path check</h3><div className="mt-4 divide-y rounded-2xl border bg-white px-5">{audit.page.ctaJourneys.map((journey) => <div key={`${journey.text}-${journey.destination}`} className="grid gap-2 py-5 text-sm md:grid-cols-[1fr_1.4fr_1fr_auto]"><strong>{journey.text}</strong><span className="truncate text-muted-foreground">{journey.destination}</span><span>{journey.outcome}</span><ExternalLink className="size-4 text-muted-foreground" /></div>)}</div></div> : null}</section>

      <section id="analysis" className="border-y bg-white"><div className="mx-auto max-w-[1500px] px-5 py-20 md:px-8"><div className="flex flex-col justify-between gap-5 border-b pb-8 md:flex-row md:items-end"><div><span className="eyebrow">Deep analysis</span><h2 className="display mt-7 text-7xl md:text-8xl">Eight expert lenses.</h2></div><p className="max-w-md text-sm leading-6 text-muted-foreground">Each specialist reads the same page evidence from a different angle. Their findings are combined and de-duplicated in your priorities.</p></div><div className="divide-y">{report.sections.map((section, index) => <details key={section.key} className="group py-2" open={index === 0}><summary className="flex cursor-pointer list-none items-center gap-5 py-6"><span className="font-mono text-xs text-muted-foreground">0{index + 1}</span><h3 className="flex-1 text-xl font-bold">{labels[section.key]}</h3><span className="font-mono text-2xl font-bold">{section.score}</span><span className="grid size-8 place-items-center rounded-full border transition group-open:rotate-45">+</span></summary><div className="grid gap-6 pb-8 pl-10 lg:grid-cols-[.55fr_1.45fr]"><p className="max-w-sm text-sm leading-6 text-muted-foreground">{section.summary}</p><div className="grid gap-3">{section.findings.map((item) => <div key={item.title} className="rounded-xl border bg-background p-5"><div className="flex flex-wrap items-center gap-2"><h4 className="font-bold">{item.title}</h4><Badge variant={badgeVariant(item.impact)}>{item.impact}</Badge></div><p className="mt-3 text-xs leading-5 text-muted-foreground">{item.evidence}</p><p className="mt-3 text-sm font-bold">→ {item.recommendation}</p></div>)}</div></div></details>)}</div></div></section>

      <section id="copy" className="bg-accent-soft"><div className="mx-auto max-w-[1500px] px-5 py-20 md:px-8"><div className="grid gap-12 lg:grid-cols-[.6fr_1.4fr]"><div><Sparkles className="size-8" /><h2 className="display mt-6 text-7xl md:text-8xl">Say it better.</h2><p className="mt-6 max-w-sm text-sm leading-6 text-muted-foreground">Ready-to-test rewrites based on the offer and evidence already on your page.</p></div><div className="space-y-4">{report.copySuggestions.map((suggestion) => <article key={suggestion.label} className="rounded-2xl border bg-white p-6 md:p-8"><Badge>{suggestion.label}</Badge><div className="mt-6 grid gap-6 md:grid-cols-[1fr_auto_1fr]"><div><span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Before</span><p className="mt-2 text-lg text-muted-foreground line-through decoration-red-400/70">{suggestion.before}</p></div><ChevronRight className="hidden size-5 self-center text-muted-foreground md:block" /><div><span className="text-[10px] font-bold uppercase tracking-widest text-foreground">After</span><p className="mt-2 text-lg font-bold">{suggestion.after}</p></div></div><p className="mt-6 border-t pt-4 text-xs leading-5 text-muted-foreground">{suggestion.rationale}</p></article>)}</div></div></div></section>

      <section id="technical" className="bg-foreground text-white"><div className="mx-auto max-w-[1500px] px-5 py-20 md:px-8"><span className="eyebrow">Technical snapshot</span><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Performance", metrics.performanceScore, Gauge], ["Accessibility", metrics.accessibilityScore, Target], ["SEO", metrics.seoScore, Sparkles], ["Best practices", metrics.bestPracticesScore, Check]].map(([label, value, Icon]) => { const MetricIcon = Icon as typeof Gauge; return <div key={String(label)} className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><MetricIcon className="size-5 text-primary" /><strong className="display mt-8 block text-6xl">{String(value)}</strong><span className="text-xs font-bold text-white/45">{String(label)}</span></div>; })}</div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["LCP", metric(metrics.lcp, "ms")], ["CLS", metric(metrics.cls)], ["TBT / INP", metric(metrics.inpOrTbt, "ms")], ["TTFB", metric(metrics.ttfb, "ms")]].map(([label, value]) => <div key={label} className="flex items-center justify-between border-b border-white/15 py-5"><span className="text-xs text-white/45">{label}</span><strong className="font-mono">{value}</strong></div>)}</div>{metrics.imageIssues.length > 0 && <div className="mt-8 flex gap-3 rounded-xl border border-amber-300/20 bg-amber-300/5 p-5 text-sm"><AlertTriangle className="size-5 shrink-0 text-amber-300" /><div><strong>Image opportunity</strong><p className="mt-1 text-white/50">{metrics.imageIssues.join(" · ")}</p></div></div>}</div></section>

      <section className="mx-auto max-w-[1500px] px-5 py-20 md:px-8"><div className="grid gap-12 lg:grid-cols-2"><div><span className="eyebrow">Quick wins</span><div className="mt-7 space-y-3">{report.quickWins.map((item) => <div key={item} className="flex gap-3 rounded-xl border bg-white p-5 text-sm font-bold"><span className="grid size-5 shrink-0 place-items-center rounded-full bg-primary"><Check className="size-3" /></span>{item}</div>)}</div></div><div><span className="eyebrow">Longer-term</span><div className="mt-7 space-y-3">{report.longTermImprovements.map((item, index) => <div key={item} className="flex gap-4 border-b py-5 text-sm"><span className="font-mono text-xs text-muted-foreground">0{index + 1}</span><span className="font-bold">{item}</span></div>)}</div></div></div></section>
    </main>
    <footer className="border-t bg-white"><div className="mx-auto flex max-w-[1500px] flex-col justify-between gap-4 px-5 py-8 text-xs text-muted-foreground md:flex-row md:px-8"><span>Report generated by Lensiq · Validate recommendations with real customer data.</span><Link href="/#audit" className="font-bold text-foreground">Audit another website →</Link></div></footer>
  </div>;
}
